classdef FunctionSpace < handle
    % FUNCTIONSPACE Base class for finite element function spaces.
    %
    %   FunctionSpace provides an abstract representation of a function
    %   space generated by an element. This class serves as the foundation
    %   for specialized function spaces such as mesh spaces, affine spaces,
    %   and scaled variants.
    %
    % See also:
    %   approx.space.MeshSpace, 
    %   approx.space.AffineSpace, 
    %   approx.space.ScaledAffineSpace
    
    properties
        element % Finite element
    end

    properties (Dependent)
        nDims % Number of dimensions
    end
    
    methods
        function obj = FunctionSpace(element)
            % FUNCTIONSPACE Constructor for FunctionSpace.
            %
            %   obj = FunctionSpace(element) creates a function element
            %   space using the specified element representation.
            %
            % Inputs:
            %   element - Element object that generates the space
            %
            % Outputs:
            %   obj - Constructed FunctionSpace object
            
            obj.element = element;
        end

        function n = get.nDims(obj)
            % GET.NDIMS Returns the number of dimensions.
            
            n = obj.element.nDims;
        end
    end

    methods (Abstract)
        % EVALUATE Evaluate functions.
        Y = evaluate(obj, varargin)
    end
end